[package]
name = "serde_cbor"
version = "0.9.0"
authors = [
    "Pyfisch <pyfisch@gmail.com>",
    "Steven Fackler <sfackler@gmail.com>"]
repository = "https://github.com/pyfisch/cbor"
readme = "README.md"
license = "MIT/Apache-2.0"
description = "CBOR support for serde."
keywords = ["serde", "cbor", "serialization"]
categories = ["encoding"]
edition = "2018"

[badges]
travis-ci = { repository = "pyfisch/cbor" }
maintenance = { status = "actively-developed" }

[dependencies]
byteorder = { version = "1.0.0", default-features = false }
half = "1.2.0"
serde = { version = "1.0.14", default-features = false }
serde_derive = { version = "1.0.14", default-features = false }

[dev-dependencies]
serde_bytes = { version = "0.10", default-features = false }

[features]
default = ["std"]
std = ["serde/std", "serde_bytes/std" ]
unsealed_read_write = []
