[package]
name = "ipld"
version = "0.1.0"
authors = ["dignifiedquire <dignifiedquire@gmail.com>"]
readme = "README.md"
license = "MIT"

[dependencies]
serde_cbor = { git = "https://github.com/pyfisch/cbor"}
