[package]
name = "fisher_yates_shuffle"
version = "0.1.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2018"

[[bench]]
name = "benches"
harness = false

[dev-dependencies]
criterion = "0.2"
yaml-rust = "0.4.2"

[dependencies]
hashing = { path = "../hashing" }
