[package]
name = "cid"
version = "0.3.0"
description = "CID in rust"
homepage = "https://github.com/multiformats/rust-cid"
authors = ["Friedel Ziegelmayer <dignifiedquire@gmail.com>"]

keywords = ["ipld", "ipfs", "cid", "multihash", "multiformats"]

license = "MIT"

readme = "README.md"

[dependencies]
multihash = "~0.8.0"
multibase = "~0.6.0"
integer-encoding = "~1.0.3"

[package.metadata.release]
upload-doc = true
pre-release-commit-message = "Release {{version}} 🎉🎉"
no-dev-version = true
