[package]
name                      = "ipfs-api"
description               = "Implementation of an IPFS HTTP API client"
authors                   = ["Ferris Tseng <ferristseng@fastmail.fm>"]
documentation             = "https://docs.rs/ipfs-api"
repository                = "https://github.com/ferristseng/rust-ipfs-api"
keywords                  = ["ipfs"]
categories                = ["filesystem", "web-programming"]
version                   = "0.5.1"
readme                    = "../README.md"
license                   = "MIT OR Apache-2.0"

[badges]
travis-ci                 = { repository = "ferristseng/rust-ipfs-api" }

[features]
default                   = ["hyper", "hyper-multipart-rfc7578", "hyper-tls"]
actix                     = ["actix-web", "actix-multipart-rfc7578"]

[dependencies]
actix-multipart-rfc7578   = { version = "0.1", optional = true }
actix-web                 = { version = "0.7", optional = true }
bytes                     = "0.4"
failure                   = "0.1.2"
futures                   = "0.1"
http                      = "0.1"
hyper                     = { version = "0.12", optional = true }
hyper-tls                 = { version = "0.3.2", optional = true }
hyper-multipart-rfc7578   = { version = "0.3", optional = true }
serde                     = "1.0"
serde_derive              = "1.0"
serde_json                = "1.0"
serde_urlencoded          = "0.5"
tokio                     = "0.1"
tokio-codec               = "0.1"
tokio-io                  = "0.1"
walkdir                   = "2.2"
dirs                      = "1.0"
multiaddr                 = "0.3.1"

[dev-dependencies]
actix-multipart-rfc7578   = "0.1"
actix-web                 = "0.7"
hyper                     = "0.12"
hyper-tls                 = "0.3.2"
tokio-timer               = "0.2"
tar                       = "0.4"
